name: 'Report jUnit Annotations as Github Actions Annotations'
description: 'Create an annotation of the Junit output'
branding:
  icon: 'box'  
  color: 'green'
inputs:
  stripFromPath:
    description: 'Path to strip from file'
    required: false
  path:
    description: 'glob to junit xml files'
    required: true
  errorLevel:
    description: 'Error level in Annotations (warning, error)'
    default: 'warning'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'